package com.cars.model;
// Generated 6 juin 2018 18:04:52 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "BOOKING")
public class Booking implements java.io.Serializable {

	private BigDecimal bookingId;
	private Gadget gadget;
	private Insurance insurance;
	private Vehicles vehicles;
	private Date bookingFromDate;
	private Date bookingToDate;
	private BigDecimal bookingEmailConfirmation;
	private BigDecimal fuelFee;
	private BigDecimal repairFee;
	private double cost;
	private Set<Custumer> custumers = new HashSet<Custumer>(0);

	public Booking() {
	}

	public Booking(BigDecimal bookingId, Vehicles vehicles, Date bookingFromDate, Date bookingToDate,
			BigDecimal bookingEmailConfirmation, BigDecimal fuelFee, BigDecimal repairFee, double cost) {
		this.bookingId = bookingId;
		this.vehicles = vehicles;
		this.bookingFromDate = bookingFromDate;
		this.bookingToDate = bookingToDate;
		this.bookingEmailConfirmation = bookingEmailConfirmation;
		this.fuelFee = fuelFee;
		this.repairFee = repairFee;
		this.cost = cost;
	}

	public Booking(BigDecimal bookingId, Gadget gadget, Insurance insurance, Vehicles vehicles, Date bookingFromDate,
			Date bookingToDate, BigDecimal bookingEmailConfirmation, BigDecimal fuelFee, BigDecimal repairFee,
			double cost, Set<Custumer> custumers) {
		this.bookingId = bookingId;
		this.gadget = gadget;
		this.insurance = insurance;
		this.vehicles = vehicles;
		this.bookingFromDate = bookingFromDate;
		this.bookingToDate = bookingToDate;
		this.bookingEmailConfirmation = bookingEmailConfirmation;
		this.fuelFee = fuelFee;
		this.repairFee = repairFee;
		this.cost = cost;
		this.custumers = custumers;
	}

	@Id

	@Column(name = "BOOKING_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(BigDecimal bookingId) {
		this.bookingId = bookingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GADGET_ID")
	public Gadget getGadget() {
		return this.gadget;
	}

	public void setGadget(Gadget gadget) {
		this.gadget = gadget;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INSURANCE_ID")
	public Insurance getInsurance() {
		return this.insurance;
	}

	public void setInsurance(Insurance insurance) {
		this.insurance = insurance;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VEHICLE_ID", nullable = false)
	public Vehicles getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Vehicles vehicles) {
		this.vehicles = vehicles;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BOOKING_FROM_DATE", nullable = false, length = 7)
	public Date getBookingFromDate() {
		return this.bookingFromDate;
	}

	public void setBookingFromDate(Date bookingFromDate) {
		this.bookingFromDate = bookingFromDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BOOKING_TO_DATE", nullable = false, length = 7)
	public Date getBookingToDate() {
		return this.bookingToDate;
	}

	public void setBookingToDate(Date bookingToDate) {
		this.bookingToDate = bookingToDate;
	}

	@Column(name = "BOOKING_EMAIL_CONFIRMATION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getBookingEmailConfirmation() {
		return this.bookingEmailConfirmation;
	}

	public void setBookingEmailConfirmation(BigDecimal bookingEmailConfirmation) {
		this.bookingEmailConfirmation = bookingEmailConfirmation;
	}

	@Column(name = "FUEL_FEE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getFuelFee() {
		return this.fuelFee;
	}

	public void setFuelFee(BigDecimal fuelFee) {
		this.fuelFee = fuelFee;
	}

	@Column(name = "REPAIR_FEE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRepairFee() {
		return this.repairFee;
	}

	public void setRepairFee(BigDecimal repairFee) {
		this.repairFee = repairFee;
	}

	@Column(name = "COST", nullable = false, precision = 126, scale = 0)
	public double getCost() {
		return this.cost;
	}

	public void setCost(double cost) {
		this.cost = cost;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "bookings")
	public Set<Custumer> getCustumers() {
		return this.custumers;
	}

	public void setCustumers(Set<Custumer> custumers) {
		this.custumers = custumers;
	}

}
