package com.cars.model;
// Generated 6 juin 2018 18:04:52 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Custumer generated by hbm2java
 */
@Entity
@Table(name = "CUSTUMER")
public class Custumer implements java.io.Serializable {

	private BigDecimal custumerId;
	private BigDecimal custumerDrivingId;
	private String custumerFirstName;
	private String custumerSecondName;
	private String emailAdress;
	private BigDecimal contactNumber;
	private String adress;
	private BigDecimal zipCode;
	private String city;
	private String state;
	private String country;
	private Set<Booking> bookings = new HashSet<Booking>(0);

	public Custumer() {
	}

	public Custumer(BigDecimal custumerId, BigDecimal custumerDrivingId, String custumerFirstName,
			String custumerSecondName, String emailAdress, BigDecimal contactNumber, String adress, BigDecimal zipCode,
			String city, String country) {
		this.custumerId = custumerId;
		this.custumerDrivingId = custumerDrivingId;
		this.custumerFirstName = custumerFirstName;
		this.custumerSecondName = custumerSecondName;
		this.emailAdress = emailAdress;
		this.contactNumber = contactNumber;
		this.adress = adress;
		this.zipCode = zipCode;
		this.city = city;
		this.country = country;
	}

	public Custumer(BigDecimal custumerId, BigDecimal custumerDrivingId, String custumerFirstName,
			String custumerSecondName, String emailAdress, BigDecimal contactNumber, String adress, BigDecimal zipCode,
			String city, String state, String country, Set<Booking> bookings) {
		this.custumerId = custumerId;
		this.custumerDrivingId = custumerDrivingId;
		this.custumerFirstName = custumerFirstName;
		this.custumerSecondName = custumerSecondName;
		this.emailAdress = emailAdress;
		this.contactNumber = contactNumber;
		this.adress = adress;
		this.zipCode = zipCode;
		this.city = city;
		this.state = state;
		this.country = country;
		this.bookings = bookings;
	}

	@Id

	@Column(name = "CUSTUMER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCustumerId() {
		return this.custumerId;
	}

	public void setCustumerId(BigDecimal custumerId) {
		this.custumerId = custumerId;
	}

	@Column(name = "CUSTUMER_DRIVING_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCustumerDrivingId() {
		return this.custumerDrivingId;
	}

	public void setCustumerDrivingId(BigDecimal custumerDrivingId) {
		this.custumerDrivingId = custumerDrivingId;
	}

	@Column(name = "CUSTUMER_FIRST_NAME", nullable = false, length = 20)
	public String getCustumerFirstName() {
		return this.custumerFirstName;
	}

	public void setCustumerFirstName(String custumerFirstName) {
		this.custumerFirstName = custumerFirstName;
	}

	@Column(name = "CUSTUMER_SECOND_NAME", nullable = false, length = 20)
	public String getCustumerSecondName() {
		return this.custumerSecondName;
	}

	public void setCustumerSecondName(String custumerSecondName) {
		this.custumerSecondName = custumerSecondName;
	}

	@Column(name = "EMAIL_ADRESS", nullable = false, length = 30)
	public String getEmailAdress() {
		return this.emailAdress;
	}

	public void setEmailAdress(String emailAdress) {
		this.emailAdress = emailAdress;
	}

	@Column(name = "CONTACT_NUMBER", nullable = false, precision = 22, scale = 0)
	public BigDecimal getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(BigDecimal contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "ADRESS", nullable = false, length = 20)
	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	@Column(name = "ZIP_CODE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(BigDecimal zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "CITY", nullable = false, length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTRY", nullable = false, length = 20)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "CUST_BOOK", joinColumns = {
			@JoinColumn(name = "CUSTUMER_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "BOOKING_ID", nullable = false, updatable = false) })
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
