package com.cars.model;
// Generated 6 juin 2018 18:04:52 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Insurance generated by hbm2java
 */
@Entity
@Table(name = "INSURANCE")
public class Insurance implements java.io.Serializable {

	private BigDecimal insuranceId;
	private String insType;
	private Set<Booking> bookings = new HashSet<Booking>(0);

	public Insurance() {
	}

	public Insurance(BigDecimal insuranceId, String insType) {
		this.insuranceId = insuranceId;
		this.insType = insType;
	}

	public Insurance(BigDecimal insuranceId, String insType, Set<Booking> bookings) {
		this.insuranceId = insuranceId;
		this.insType = insType;
		this.bookings = bookings;
	}

	@Id

	@Column(name = "INSURANCE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getInsuranceId() {
		return this.insuranceId;
	}

	public void setInsuranceId(BigDecimal insuranceId) {
		this.insuranceId = insuranceId;
	}

	@Column(name = "INS_TYPE", nullable = false, length = 30)
	public String getInsType() {
		return this.insType;
	}

	public void setInsType(String insType) {
		this.insType = insType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "insurance")
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
