package com.cars.model;
// Generated 15 juin 2018 16:18:35 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MenuTree generated by hbm2java
 */
@Entity
@Table(name = "MENU_TREE")
public class MenuTree implements java.io.Serializable {

	private long menuId;
	private MenuTree menuTree;
	private String definition;
	private long displaySeq;
	private long indicMenu;
	private String menuName;
	private String menuType;
	private String pageTrac;
	private String taskflow;
	private String utilTrac;
	private Set<ProfilMenuTree> profilMenuTrees = new HashSet<ProfilMenuTree>(0);
	private Set<UsrMenTree> usrMenTrees = new HashSet<UsrMenTree>(0);
	private Set<MenuTree> menuTrees = new HashSet<MenuTree>(0);

	public MenuTree() {
	}

	public MenuTree(long menuId) {
		this.menuId = menuId;
	}

	public MenuTree(long menuId, MenuTree menuTree, String definition, long displaySeq, long indicMenu, String menuName,
			String menuType, String pageTrac, String taskflow, String utilTrac, Set<ProfilMenuTree> profilMenuTrees,
			Set<UsrMenTree> usrMenTrees, Set<MenuTree> menuTrees) {
		this.menuId = menuId;
		this.menuTree = menuTree;
		this.definition = definition;
		this.displaySeq = displaySeq;
		this.indicMenu = indicMenu;
		this.menuName = menuName;
		this.menuType = menuType;
		this.pageTrac = pageTrac;
		this.taskflow = taskflow;
		this.utilTrac = utilTrac;
		this.profilMenuTrees = profilMenuTrees;
		this.usrMenTrees = usrMenTrees;
		this.menuTrees = menuTrees;
	}

	@Id

	@Column(name = "MENU_ID", unique = true, nullable = false, scale = 0)
	public long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(long menuId) {
		this.menuId = menuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_MENU_ID")
	public MenuTree getMenuTree() {
		return this.menuTree;
	}

	public void setMenuTree(MenuTree menuTree) {
		this.menuTree = menuTree;
	}

	@Column(name = "DEFINITION", length = 800)
	public String getDefinition() {
		return this.definition;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}

	@Column(name = "DISPLAY_SEQ", scale = 0)
	public long getDisplaySeq() {
		return this.displaySeq;
	}

	public void setDisplaySeq(long displaySeq) {
		this.displaySeq = displaySeq;
	}

	@Column(name = "INDIC_MENU", scale = 0)
	public long getIndicMenu() {
		return this.indicMenu;
	}

	public void setIndicMenu(long indicMenu) {
		this.indicMenu = indicMenu;
	}

	@Column(name = "MENU_NAME", length = 400)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "MENU_TYPE", length = 4)
	public String getMenuType() {
		return this.menuType;
	}

	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}

	@Column(name = "PAGE_TRAC", length = 1000)
	public String getPageTrac() {
		return this.pageTrac;
	}

	public void setPageTrac(String pageTrac) {
		this.pageTrac = pageTrac;
	}

	@Column(name = "TASKFLOW", length = 400)
	public String getTaskflow() {
		return this.taskflow;
	}

	public void setTaskflow(String taskflow) {
		this.taskflow = taskflow;
	}

	@Column(name = "UTIL_TRAC", length = 120)
	public String getUtilTrac() {
		return this.utilTrac;
	}

	public void setUtilTrac(String utilTrac) {
		this.utilTrac = utilTrac;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuTree")
	public Set<ProfilMenuTree> getProfilMenuTrees() {
		return this.profilMenuTrees;
	}

	public void setProfilMenuTrees(Set<ProfilMenuTree> profilMenuTrees) {
		this.profilMenuTrees = profilMenuTrees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuTree")
	public Set<UsrMenTree> getUsrMenTrees() {
		return this.usrMenTrees;
	}

	public void setUsrMenTrees(Set<UsrMenTree> usrMenTrees) {
		this.usrMenTrees = usrMenTrees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuTree")
	public Set<MenuTree> getMenuTrees() {
		return this.menuTrees;
	}

	public void setMenuTrees(Set<MenuTree> menuTrees) {
		this.menuTrees = menuTrees;
	}

}
