package com.cars.model;
// Generated 15 juin 2018 16:18:35 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProfilMenuTree generated by hbm2java
 */
@Entity
@Table(name = "PROFIL_MENU_TREE")
public class ProfilMenuTree implements java.io.Serializable {

	private ProfilMenuTreeId id;
	private MenuTree menuTree;
	private Profil profil;
	private long del;
	private long ins;
	private String pageTrac;
	private long upd;
	private String utilTrac;

	public ProfilMenuTree() {
	}

	public ProfilMenuTree(ProfilMenuTreeId id, MenuTree menuTree, Profil profil) {
		this.id = id;
		this.menuTree = menuTree;
		this.profil = profil;
	}

	public ProfilMenuTree(ProfilMenuTreeId id, MenuTree menuTree, Profil profil, long del, long ins, String pageTrac,
			long upd, String utilTrac) {
		this.id = id;
		this.menuTree = menuTree;
		this.profil = profil;
		this.del = del;
		this.ins = ins;
		this.pageTrac = pageTrac;
		this.upd = upd;
		this.utilTrac = utilTrac;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codeProfil", column = @Column(name = "CODE_PROFIL", nullable = false, scale = 0)),
			@AttributeOverride(name = "menuId", column = @Column(name = "MENU_ID", nullable = false, scale = 0)) })
	public ProfilMenuTreeId getId() {
		return this.id;
	}

	public void setId(ProfilMenuTreeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MENU_ID", nullable = false, insertable = false, updatable = false)
	public MenuTree getMenuTree() {
		return this.menuTree;
	}

	public void setMenuTree(MenuTree menuTree) {
		this.menuTree = menuTree;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_PROFIL", nullable = false, insertable = false, updatable = false)
	public Profil getProfil() {
		return this.profil;
	}

	public void setProfil(Profil profil) {
		this.profil = profil;
	}

	@Column(name = "DEL", scale = 0)
	public long getDel() {
		return this.del;
	}

	public void setDel(long del) {
		this.del = del;
	}

	@Column(name = "INS", scale = 0)
	public long getIns() {
		return this.ins;
	}

	public void setIns(long ins) {
		this.ins = ins;
	}

	@Column(name = "PAGE_TRAC", length = 1000)
	public String getPageTrac() {
		return this.pageTrac;
	}

	public void setPageTrac(String pageTrac) {
		this.pageTrac = pageTrac;
	}

	@Column(name = "UPD", scale = 0)
	public long getUpd() {
		return this.upd;
	}

	public void setUpd(long upd) {
		this.upd = upd;
	}

	@Column(name = "UTIL_TRAC", length = 120)
	public String getUtilTrac() {
		return this.utilTrac;
	}

	public void setUtilTrac(String utilTrac) {
		this.utilTrac = utilTrac;
	}

}
