package com.cars.model;
// Generated 15 juin 2018 16:18:35 by Hibernate Tools 4.3.5.Final

import java.sql.Blob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PsTxn generated by hbm2java
 */
@Entity
@Table(name = "PS_TXN")
public class PsTxn implements java.io.Serializable {

	private PsTxnId id;
	private long parentid;
	private Blob content;
	private Date creationDate;

	public PsTxn() {
	}

	public PsTxn(PsTxnId id) {
		this.id = id;
	}

	public PsTxn(PsTxnId id, long parentid, Blob content, Date creationDate) {
		this.id = id;
		this.parentid = parentid;
		this.content = content;
		this.creationDate = creationDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "collid", column = @Column(name = "COLLID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, precision = 20, scale = 0)) })
	public PsTxnId getId() {
		return this.id;
	}

	public void setId(PsTxnId id) {
		this.id = id;
	}

	@Column(name = "PARENTID", precision = 20, scale = 0)
	public long getParentid() {
		return this.parentid;
	}

	public void setParentid(long parentid) {
		this.parentid = parentid;
	}

	@Column(name = "CONTENT")
	public Blob getContent() {
		return this.content;
	}

	public void setContent(Blob content) {
		this.content = content;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATION_DATE", length = 7)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
