package com.cars.model;
// Generated 15 juin 2018 16:18:35 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PsTxnId generated by hbm2java
 */
@Embeddable
public class PsTxnId implements java.io.Serializable {

	private long collid;
	private long id;

	public PsTxnId() {
	}

	public PsTxnId(long collid, long id) {
		this.collid = collid;
		this.id = id;
	}

	@Column(name = "COLLID", nullable = false, precision = 10, scale = 0)
	public long getCollid() {
		return this.collid;
	}

	public void setCollid(long collid) {
		this.collid = collid;
	}

	@Column(name = "ID", nullable = false, precision = 20, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PsTxnId))
			return false;
		PsTxnId castOther = (PsTxnId) other;

		return (this.getCollid() == castOther.getCollid()) && (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCollid();
		result = 37 * result + (int) this.getId();
		return result;
	}

}
