package com.cars.model;
// Generated 6 juin 2018 18:04:52 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * Vehicles generated by hbm2java
 */
@Entity
@Table(name = "VEHICLES")
public class Vehicles implements java.io.Serializable {

	@NotNull
	private Long vehicleId;

	@NotNull
	private Brand brand;

	@NotNull
	@Min(0)
	private Long vehicleCurrentKm;

	@NotNull
	@DecimalMin("1.5")
	private double carEngineSize;

	@NotNull
	@Min(1000)
	private Long price;

	private Set<VehAv> vehAvs = new HashSet<VehAv>(0);
	private Set<Booking> bookings = new HashSet<Booking>(0);

	public Vehicles() {
	}

	public Vehicles(Long vehicleId, Brand brand, Long vehicleCurrentKm, double carEngineSize, Long price) {
		this.vehicleId = vehicleId;
		this.brand = brand;
		this.vehicleCurrentKm = vehicleCurrentKm;
		this.carEngineSize = carEngineSize;
		this.price = price;
	}

	public Vehicles(Long vehicleId, Brand brand, Long vehicleCurrentKm, double carEngineSize, Long price,
			Set<VehAv> vehAvs, Set<Booking> bookings) {
		this.vehicleId = vehicleId;
		this.brand = brand;
		this.vehicleCurrentKm = vehicleCurrentKm;
		this.carEngineSize = carEngineSize;
		this.price = price;
		this.vehAvs = vehAvs;
		this.bookings = bookings;
	}

	@Id

	@Column(name = "VEHICLE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Long vehicleId) {
		this.vehicleId = vehicleId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "BRAND_ID", nullable = false)
	public Brand getBrand() {
		return this.brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	@Column(name = "VEHICLE_CURRENT_KM", nullable = false, precision = 22, scale = 0)
	public Long getVehicleCurrentKm() {
		return this.vehicleCurrentKm;
	}

	public void setVehicleCurrentKm(Long vehicleCurrentKm) {
		this.vehicleCurrentKm = vehicleCurrentKm;
	}

	@Column(name = "CAR_ENGINE_SIZE", nullable = false, precision = 126, scale = 0)
	public double getCarEngineSize() {
		return this.carEngineSize;
	}

	public void setCarEngineSize(double carEngineSize) {
		this.carEngineSize = carEngineSize;
	}

	@Column(name = "PRICE", nullable = false, precision = 22, scale = 0)
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "vehicles")
	public Set<VehAv> getVehAvs() {
		return this.vehAvs;
	}

	public void setVehAvs(Set<VehAv> vehAvs) {
		this.vehAvs = vehAvs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicles")
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
